## Dataset Description `customer_train.csv`:

| Column                   | Description                                                                      |
|------------------------- |--------------------------------------------------------------------------------- |
| `student_id`             | A unique ID for each student.                                                    |
| `city`                   | A code for the city the student lives in.                                        |
| `city_development_index` | A scaled development index for the city.                                         |
| `gender`                 | The student's gender.                                                            |
| `relevant_experience`    | An indicator of the student's work relevant experience.                          |
| `enrolled_university`    | The type of university course enrolled in (if any).                              |
| `education_level`        | The student's education level.                                                   |
| `major_discipline`       | The educational discipline of the student.                                       |
| `experience`             | The student's total work experience (in years).                                  |
| `company_size`           | The number of employees at the student's current employer.                       |
| `company_type`           | The type of company employing the student.                                       |
| `last_new_job`           | The number of years between the student's current and previous jobs.             |
| `training_hours`         | The number of hours of training completed.                                       |
| `job_change`             | An indicator of whether the student is looking for a new job (`1`) or not (`0`). |

## Import necessary libraries & Loading the dataset

In [89]:
# Import necessary libraries
import pandas as pd

# Load the dataset
ds_jobs = pd.read_csv("customer_train.csv")

# View the dataset
ds_jobs.head()

   student_id      city  ...  training_hours job_change
0        8949  city_103  ...              36        1.0
1       29725   city_40  ...              47        0.0
2       11561   city_21  ...              83        0.0
3       33241  city_115  ...              52        1.0
4         666  city_162  ...               8        0.0

[5 rows x 14 columns]

## Exploratory data analysis

In [ ]:
# Creating a copy of ds_jobs for transforming
ds_jobs_transformed = ds_jobs.copy()
ds_jobs_transformed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevant_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  job_change              19158 non-null  float64
dtypes: float64(2), int64(2), object(10)
memory usage: 2.0+ MB

In [91]:
ds_jobs_transformed.columns[ds_jobs_transformed.nunique() == 2]

Index(['relevant_experience', 'job_change'], dtype='object')

In [92]:
ds_jobs_transformed['relevant_experience'].unique()

array(['Has relevant experience', 'No relevant experience'], dtype=object)

In [93]:
ds_jobs_transformed['job_change'].unique()

array([1., 0.])

## Converting integers, floats, and unordered categories

In [94]:
ds_jobs_transformed['relevant_experience'] = ds_jobs_transformed['relevant_experience'].map({'Has relevant experience' : True, 'No relevant experience' : False})

ds_jobs_transformed['job_change'] = ds_jobs_transformed['job_change'].map({1 : True, 0 : False})

ds_jobs_transformed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevant_experience     19158 non-null  bool
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  job_change              19158 non-null  bool
dtypes: bool(2), float64(1), int64(2), object(9)
memory usage: 1.8+ MB

In [95]:
ds_jobs_transformed.head()

   student_id      city  ...  training_hours job_change
0        8949  city_103  ...              36       True
1       29725   city_40  ...              47      False
2       11561   city_21  ...              83      False
3       33241  city_115  ...              52       True
4         666  city_162  ...               8      False

[5 rows x 14 columns]

In [96]:
ds_jobs_transformed[['student_id', 'training_hours']] = ds_jobs_transformed[['student_id', 'training_hours']].astype('int32')
ds_jobs_transformed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              19158 non-null  int32
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevant_experience     19158 non-null  bool
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int32
 13  job_change              19158 non-null  bool
dtypes: bool(2), float64(1), int32(2), object(9)
memory usage: 1.6+ MB

In [97]:
ds_jobs_transformed['city_development_index'] = ds_jobs_transformed['city_development_index'].astype('float16')
ds_jobs_transformed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              19158 non-null  int32
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float16
 3   gender                  14650 non-null  object
 4   relevant_experience     19158 non-null  bool
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int32
 13  job_change              19158 non-null  bool
dtypes: bool(2), float16(1), int32(2), object(9)
memory usage: 1.5+ MB

In [98]:
ds_jobs_transformed[['gender', 'city', 'major_discipline', 'company_type']] = ds_jobs_transformed[['gender', 'city', 'major_discipline', 'company_type']].astype('category')
ds_jobs_transformed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              19158 non-null  int32
 1   city                    19158 non-null  category
 2   city_development_index  19158 non-null  float16
 3   gender                  14650 non-null  category
 4   relevant_experience     19158 non-null  bool
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  category
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  category
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int32
 13  job_change              19158 non-null  bool
dtypes: bool(2), category(4), float16(1), int32(2), object(5)
memory usage: 1.0+ MB

In [99]:
ds_jobs_transformed['enrolled_university'].unique()

array(['no_enrollment', 'Full time course', nan, 'Part time course'],
      dtype=object)

In [100]:
ds_jobs_transformed['education_level'].unique()

array(['Graduate', 'Masters', 'High School', nan, 'Phd', 'Primary School'],
      dtype=object)

In [101]:
ds_jobs_transformed['experience'].unique()

array(['>20', '15', '5', '<1', '11', '13', '7', '17', '2', '16', '1', '4',
       '10', '14', '18', '19', '12', '3', '6', '9', '8', '20', nan],
      dtype=object)

In [102]:
ds_jobs_transformed['company_size'].unique()

array([nan, '50-99', '<10', '10000+', '5000-9999', '1000-4999', '10-49',
       '100-499', '500-999'], dtype=object)

In [103]:
ds_jobs_transformed['last_new_job'].unique()

array(['1', '>4', 'never', '4', '3', '2', nan], dtype=object)

## Converting ordered categories

In [104]:
from pandas.api.types import CategoricalDtype 

enrolled_university_order = ['no_enrollment', 'Part time course', 'Full time course']
education_level_order = ['Primary School', 'High School', 'Graduate', 'Masters', 'Phd']
experience_order = ['<1', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '>20']
company_size_order = ['<10', '10-49', '50-99', '100-499', '500-999', '1000-4999', '5000-9999', '10000+']
last_new_job_order = ['never', '1', '2', '3', '4', '>4']

ds_jobs_transformed['enrolled_university'] = ds_jobs_transformed['enrolled_university'].astype(
    CategoricalDtype(categories=enrolled_university_order, ordered=True)
)
ds_jobs_transformed['education_level'] = ds_jobs_transformed['education_level'].astype(
    CategoricalDtype(categories=education_level_order, ordered=True)
)
ds_jobs_transformed['experience'] = ds_jobs_transformed['experience'].astype(
    CategoricalDtype(categories=experience_order, ordered=True)
)
ds_jobs_transformed['company_size'] = ds_jobs_transformed['company_size'].astype(
    CategoricalDtype(categories=company_size_order, ordered=True)
)
ds_jobs_transformed['last_new_job'] = ds_jobs_transformed['last_new_job'].astype(
    CategoricalDtype(categories=last_new_job_order, ordered=True)
)

ds_jobs_transformed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              19158 non-null  int32
 1   city                    19158 non-null  category
 2   city_development_index  19158 non-null  float16
 3   gender                  14650 non-null  category
 4   relevant_experience     19158 non-null  bool
 5   enrolled_university     18772 non-null  category
 6   education_level         18698 non-null  category
 7   major_discipline        16345 non-null  category
 8   experience              19093 non-null  category
 9   company_size            13220 non-null  category
 10  company_type            13018 non-null  category
 11  last_new_job            18735 non-null  category
 12  training_hours          19158 non-null  int32
 13  job_change              19158 non-null  bool
dtypes: bool(2), category(9), float16(1), int32(2)
memory usage: 400.2 KB

## Filtering on ordered categorical columns

In [105]:
ds_jobs_transformed = ds_jobs_transformed[
    (ds_jobs_transformed['experience'] >= '10') & 
    (ds_jobs_transformed['company_size'] >= '1000-4999')
]
ds_jobs_transformed.head()

    student_id      city  ...  training_hours job_change
9          699  city_103  ...             123      False
12       25619   city_61  ...              23      False
31       22293  city_103  ...             141      False
34       26494   city_16  ...             145      False
40        2547  city_114  ...              14      False

[5 rows x 14 columns]

In [106]:
ds_jobs.info(), ds_jobs_transformed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevant_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  job_change              19158 non-null  float64
dtypes: float64(2), int64(2), object(10)
memory usage: 2.0+ MB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2201 entries, 9 to 19143
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              2201 non-null   int32
 1   city                    2201 non-null   category
 2   city_development_index  2201 non-null   float16
 3   gender                  1821 non-null   category
 4   relevant_experience     2201 non-null   bool
 5   enrolled_university     2185 non-null   category
 6   education_level         2184 non-null   category
 7   major_discipline        2097 non-null   category
 8   experience              2201 non-null   category
 9   company_size            2201 non-null   category
 10  company_type            2144 non-null   category
 11  last_new_job            2184 non-null   category
 12  training_hours          2201 non-null   int32
 13  job_change              2201 non-null   bool
dtypes: bool(2), category(9), float16(1), int32(2)
memory usage: 69.5 KB

(None, None)

In [107]:
ds_jobs.memory_usage(), ds_jobs_transformed.memory_usage()

(Index                        128
 student_id                153264
 city                      153264
 city_development_index    153264
 gender                    153264
 relevant_experience       153264
 enrolled_university       153264
 education_level           153264
 major_discipline          153264
 experience                153264
 company_size              153264
 company_type              153264
 last_new_job              153264
 training_hours            153264
 job_change                153264
 dtype: int64,
 Index                     17608
 student_id                 8804
 city                       7353
 city_development_index     4402
 gender                     2333
 relevant_experience        2201
 enrolled_university        2333
 education_level            2413
 major_discipline           2421
 experience                 2933
 company_size               2565
 company_type               2421
 last_new_job               2421
 training_hours             8804
 job_change                 2201
 dtype: int64)